on:
  pull_request_target:
    types: [labeled, unlabeled, opened, synchronize, reopened]

name: Changelog check

jobs:
  changelog:
    name: Changelog check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Changelog updated
        uses: Zomzog/changelog-checker@v1.3.0
        with:
          fileName: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
