name: codegen
on:
  push:
    branches: [master]
  pull_request:
  merge_group:

jobs:
  codegen:
    name: Check Codegen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          component: clippy
          target: x86_64-unknown-linux-gnu
      - run: cargo clippy -p codegen --target x86_64-unknown-linux-gnu

