name: HAL CI

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - 'Cargo.toml'
      - '.clippy.toml'
      - 'build.rs'
      - 'src/**'
      - 'examples/**'
      - '**.toml'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Devices only differ in memory size are commented out
        mcu:
          - stm32f301x6
          - stm32f318x8
          - stm32f302x6
          # - stm32f302x8
          - stm32f302xb
          # - stm32f302xc
          - stm32f302xd
          # - stm32f302xe
          - stm32f303x6
          # - stm32f303x8
          - stm32f303xb
          - stm32f303xc
          - stm32f303xd
          # - stm32f303xe
          - stm32f328x8
          - stm32f358xc
          - stm32f398xe
          - stm32f373x8
          # - stm32f373xb
          # - stm32f373xc
          - stm32f378xc
          - stm32f334x4
          # - stm32f334x6
          # - stm32f334x8
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - run: cargo build --features=${{ matrix.mcu }} --lib --examples

  # This is our MSRV. However this is only for documentation
  # purposes and should be increased if newer features are used.
  # This should not stop anyone from bumping the MSRV.
  check-msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.52.0
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=stm32f303xc,stm32-usbd,rt,can,ld --lib --examples

  check-min-deps:
    name: Check Minimal Dependency Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: thumbv7em-none-eabihf
          profile: minimal
      - run: cargo +nightly update -Z minimal-versions
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=stm32f303xc,stm32-usbd,rt,can,ld --lib --examples

  check-minimal-feature-set:
    name: Check minimal feature set
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --features=stm32f303xc --lib --examples

  build-testsuite:
    name: Build Testsuite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p testsuite --no-run

  check-doc:
    name: Check Documentation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --features=stm32f303xc

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            --features=stm32f303xc --lib --examples
            -- -D warnings

  # This is only needed, becuase workflows can not trigger other workflows
  build-testsuite:
    name: Build Testsuite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p testsuite --no-run
